kind: pipeline
name: default

steps:
- name: install
  image: node:latest
  command: npm install

- name: lint
  image: node:latest
  command: npm run lint

- name: test
  image: node:latest
  command: npm run test

when:
  branch:
  - master
  event:
  - pull_request
