kind: pipeline
name: default

steps:
  - name: test
      image: node:latest
      commands:
        - npm install
        - npm lint
        - npm test

trigger:
  branch:
    - master
  event:
    - pull-request
