kind: pipeline
name: default

steps:
- name: test
  image: node:latest
  commands:
  - npm install
  - npm lint
  - npm test
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock

when:
  event:
  - pull_request
